apiVersion: v1
kind: Service
metadata:
  name: legacy-perl-service
  namespace: default
spec:
  selector:
    app: legacy-perl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
